---
version: "2"
linters:
  settings:
    errcheck:
      exclude-functions:
        - (log/slog.Logger).Debug
        - (log/slog.Logger).Info
        - (log/slog.Logger).Warn
        - (log/slog.Logger).Error
