env: []
before:
  hooks:
    - go mod download
builds:
  - binary: openstack-exporter
    main: ./main.go
    ldflags:
      - -linkmode external -extldflags -static
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - s390x