{{- if not .Values.clouds_yaml_secret_name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-exporter.cloudsYamlSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- .Values.clouds_yaml_config | nindent 2 }}
{{- end }}
