// Code generated by go run ./script/sync-gophercloud; DO NOT EDIT.
// Source: gophercloud/gophercloud@4aae510cb4d2b51a46151542c7fbca55f8952f04/internal/acceptance/clients/conditions.go
// Copyright Gophercloud authors. Licensed under Apache-2.0; see ../LICENSE.gophercloud.

package clients

import (
	"testing"
)

// RequireLong will ensure long-running tests can run.
func RequireLong(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping test in short mode")
	}
}
