#!/bin/bash
# Run identity integration test only
set -xo pipefail

# shellcheck disable=SC1091
source "$(dirname "$0")/../stackenv"

set -eu

timeout="60m"

LOG_DIR=${LOG_DIR:-}
if [[ -z "${LOG_DIR}" ]]; then
    echo "LOG_DIR not set, will set a temp directory"
    LOG_DIR=/tmp/devstack-logs
fi
mkdir -p "${LOG_DIR}"

go test -v -timeout $timeout -tags "fixtures acceptance" ./integration -run '^TestIdentityIntegration$' |& tee -a "${LOG_DIR}/acceptance_tests.log"