// Command sync-gophercloud copies selected acceptance helpers from a pinned
// Gophercloud checkout. Run it from the repository root.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strconv"
	"strings"
)

var selections = []struct {
	source, target, pkg string
	names               []string
}{
	{"clients/clients.go", "clients/choices_generated.go", "clients", []string{"AcceptanceTestChoices", "AcceptanceTestChoicesFromEnv"}},
	{"clients/conditions.go", "clients/conditions_generated.go", "clients", []string{"RequireLong"}},
	{"tools/tools.go", "tools/tools_generated.go", "tools", []string{"WaitFor", "WaitForTimeout", "MakeNewPassword", "RandomString", "randomString", "RandomInt"}},
	{"openstack/compute/v2/compute.go", "funcs/compute_generated.go", "funcs", []string{"CreateServer", "DeleteServer", "GetNetworkIDFromNetworks", "WaitForComputeStatus"}},
	{"openstack/baremetal/v1/baremetal.go", "funcs/baremetal_generated.go", "funcs", []string{"DeleteNode", "CreateFakeNode", "ChangeProvisionStateAndWait", "DeployFakeNode"}},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	source := flag.String("source", "", "existing clean Gophercloud checkout (otherwise fetch the pinned commit)")
	flag.Parse()
	pin, err := os.ReadFile("integration/GOPHERCLOUD_REVISION")
	if err != nil {
		return err
	}
	revision := strings.TrimSpace(string(pin))
	if len(revision) != 40 || strings.Trim(revision, "0123456789abcdef") != "" {
		return fmt.Errorf("GOPHERCLOUD_REVISION must contain a full commit SHA")
	}
	if *source == "" {
		*source, err = os.MkdirTemp("", "gophercloud-helpers-*")
		if err != nil {
			return err
		}
		defer os.RemoveAll(*source)
		for _, args := range [][]string{
			{"init", "--quiet"},
			{"fetch", "--quiet", "--depth=1", "https://github.com/gophercloud/gophercloud.git", revision},
			{"checkout", "--quiet", "--detach", "FETCH_HEAD"},
		} {
			if _, err := git(*source, args...); err != nil {
				return err
			}
		}
	}
	head, err := git(*source, "rev-parse", "HEAD")
	if err != nil {
		return err
	}
	if strings.TrimSpace(string(head)) != revision {
		return fmt.Errorf("source checkout does not match pinned commit %s", revision)
	}
	status, err := git(*source, "status", "--porcelain")
	if err != nil {
		return err
	}
	if len(status) != 0 {
		return fmt.Errorf("source checkout must be clean")
	}

	// Prepare every output before writing, so missing declarations leave the
	// existing helpers untouched.
	outputs := make(map[string][]byte)
	for _, selection := range selections {
		data, err := os.ReadFile(filepath.Join(*source, "internal/acceptance", selection.source))
		if err != nil {
			return err
		}
		data, err = extract(data, selection.pkg, selection.names)
		if err != nil {
			return fmt.Errorf("%s: %w", selection.source, err)
		}
		header := fmt.Sprintf("// Code generated by go run ./script/sync-gophercloud; DO NOT EDIT.\n// Source: gophercloud/gophercloud@%s/internal/acceptance/%s\n// Copyright Gophercloud authors. Licensed under Apache-2.0; see ../LICENSE.gophercloud.\n\n", revision, selection.source)
		outputs[filepath.Join("integration", selection.target)] = append([]byte(header), data...)
	}
	license, err := os.ReadFile(filepath.Join(*source, "LICENSE"))
	if err != nil {
		return err
	}
	lines := strings.Split(string(license), "\n")
	for i := range lines {
		lines[i] = strings.TrimRight(lines[i], " \t")
	}
	outputs["integration/LICENSE.gophercloud"] = []byte(strings.Join(lines, "\n"))
	for target, data := range outputs {
		if err := os.WriteFile(target, data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func git(dir string, args ...string) ([]byte, error) {
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	data, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("git %v: %w\n%s", args, err, data)
	}
	return data, nil
}

// extract preserves the selected declarations verbatim, including comments,
// then rewrites internal imports and keeps only the imports they use.
func extract(source []byte, pkg string, names []string) ([]byte, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "source.go", source, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	wanted := make(map[string]bool)
	for _, name := range names {
		wanted[name] = true
	}
	used := make(map[string]bool)
	var body bytes.Buffer
	for _, decl := range file.Decls {
		var name string
		var doc *ast.CommentGroup
		switch decl := decl.(type) {
		case *ast.FuncDecl:
			name, doc = decl.Name.Name, decl.Doc
		case *ast.GenDecl:
			if len(decl.Specs) == 1 {
				if spec, ok := decl.Specs[0].(*ast.TypeSpec); ok {
					name, doc = spec.Name.Name, decl.Doc
				}
			}
		}
		if !wanted[name] {
			continue
		}
		delete(wanted, name)
		ast.Inspect(decl, func(node ast.Node) bool {
			if selector, ok := node.(*ast.SelectorExpr); ok {
				if ident, ok := selector.X.(*ast.Ident); ok {
					used[ident.Name] = true
				}
			}
			return true
		})
		start := decl.Pos()
		if doc != nil {
			start = doc.Pos()
		}
		body.Write(source[fset.Position(start).Offset:fset.Position(decl.End()).Offset])
		body.WriteString("\n\n")
	}
	if len(wanted) != 0 {
		return nil, fmt.Errorf("selected declarations missing: %v", wanted)
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "package %s\n\nimport (\n", pkg)
	external := false
	for _, spec := range file.Imports {
		importPath, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			return nil, err
		}
		name := path.Base(importPath)
		if version, err := strconv.Atoi(strings.TrimPrefix(name, "v")); strings.HasPrefix(name, "v") && err == nil && version >= 2 {
			name = path.Base(path.Dir(importPath))
		}
		alias := ""
		if spec.Name != nil {
			name, alias = spec.Name.Name, spec.Name.Name+" "
		}
		if used[name] {
			if strings.Contains(importPath, ".") && !external {
				output.WriteString("\n")
				external = true
			}
			importPath = strings.Replace(importPath, "github.com/gophercloud/gophercloud/v2/internal/acceptance/", "github.com/openstack-exporter/openstack-exporter/integration/", 1)
			fmt.Fprintf(&output, "%s%q\n", alias, importPath)
		}
	}
	output.WriteString(")\n\n")
	output.Write(body.Bytes())
	return format.Source(output.Bytes())
}
