name: golang-openstack-exporter
base: core22
summary: OpenStack Exporter for Prometheus
description: |
  The OpenStack exporter, exports Prometheus metrics from a running OpenStack
  cloud for consumption by prometheus.
adopt-info: openstack-exporter
confinement: strict
grade: stable

apps:
  openstack-exporter:
    daemon: simple
    restart-condition: on-abnormal
    command: "bin/openstack-exporter.wrapper"
    plugs:
      - home
      - network
      - network-bind
      - etc-openstack

parts:
  openstack-exporter:
    plugin: go
    source: ./
    source-type: git
    build-snaps:
      - go
    override-pull: |
      craftctl default
      VERSION=$(cat VERSION)
      craftctl set version="${VERSION}"
  scripts:
    plugin: dump
    source: snap/local
    organize:
      openstack-exporter.wrapper: "bin/openstack-exporter.wrapper"

plugs:
  etc-openstack:
    interface: system-files
    read:
    - /etc/openstack
