name: golang-openstack-exporter
base: core22
summary: OpenStack Exporter for Prometheus
description: |
  The OpenStack exporter, exports Prometheus metrics from a running OpenStack
  cloud for consumption by prometheus.
adopt-info: openstack-exporter
confinement: strict
grade: stable

apps:
  openstack-exporter:
    command: bin/openstack-exporter
    plugs: [home, network, network-bind]
  service:
    command: bin/service
    daemon: simple
    install-mode: disable
    restart-condition: on-abnormal
    plugs:
      - home
      - network
      - network-bind
      - etc-openstack

parts:
  openstack-exporter:
    plugin: go
    source: ./
    build-snaps:
      - go
    # override pull to read VERSION because working dir is root of source repo
    override-pull: |
      craftctl default
      craftctl set version="$(cat VERSION)"
  scripts:
    plugin: dump
    source: snap/local
    organize:
      service: bin/service

plugs:
  # The exporter reads a clouds.yaml file (path passed by the user),
  # and this file is commonly stored at /etc/openstack/clouds.yaml.
  etc-openstack:
    interface: system-files
    read:
    - /etc/openstack
