name: integration-compute
on:
  pull_request:
  workflow_dispatch:

jobs:
  integration-compute:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "24.04"
            additional_services: "openstack-cli-server"
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with Nova and run compute integration tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy devstack
        uses: gophercloud/devstack-action@60ca1042045c0c9e3e001c64575d381654ffcba1
        with:
          branch: ${{ matrix.openstack_version }}
          enabled_services: "${{ matrix.additional_services }}"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'
      - name: Display clouds.yaml configuration
        run: |
          echo "Contents of /etc/openstack/clouds.yaml:"
          cat /etc/openstack/clouds.yaml || echo "File /etc/openstack/clouds.yaml not found"
      - name: Run Openstack Integration Tests
        run: bash ./script/integration-suites/compute
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-compute-${{ matrix.name }}-${{ github.run_id }}
          path: /tmp/devstack-logs/*